---
:registers:
  zqcr:
    - ASYM_DRV_EN: 1
    - PU_ODT_ONLY: 0
    - DIS_NON_LIN_COMP: 0
    - PGWAIT: 4
  zq0pr:
    - ZQDIV: 23
    - ZPROG_ASYM_DRV_PU: 7
    - ZPROG_ASYM_DRV_PD: 7
  zq1pr:
    - ZQDIV: 23
    - ZPROG_ASYM_DRV_PU: 11
    - ZPROG_ASYM_DRV_PD: 7
  zq2pr:
    - ZQDIV: 23
    - ZPROG_ASYM_DRV_PU: 11
    - ZPROG_ASYM_DRV_PD: 7
